bidwar/Items/urls.py
from django.urls import path
from .views import (ItemList,
	ItemCreate,
	bid,
	ItemDelete,
	ItemDetail
					)
a=1
app_name='Items'
urlpatterns=[
	
	path('',ItemList.as_view(),name='home') ,
	path('add',ItemCreate.as_view(),name='add') ,
	path('bid/<int:item>',bid,name='bid') ,
	path('delete/<int:pk>',ItemDelete.as_view(),name='delete') ,
	path('detail/<int:pk>',ItemDetail.as_view(),name='detail') ,
] 

bidwar/Users/urls.py
from django.urls import path
from .views import (
					register,
					profile
					)
app_name='Users'
urlpatterns=[
	path('register/', register, name='register') ,
    path('profile/', profile, name='profile') ,

]

bidwar/bidwar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from Items.views import start_view,about_view
urlpatterns = [
	path('users/', include('Users.urls')) ,
    path('items/', include('Items.urls')) ,
    path('',start_view,name='start') ,
	path('about/',about_view,name='about') ,

    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='Users/login.html'), name='login') ,
    path('logout/', auth_views.LogoutView.as_view(template_name='Users/logout.html'), name='logout') ,
]

bidwar/Items/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

class Item(models.Model):
	name=models.CharField(max_length=20)
	description=models.TextField()
	owner= models.ForeignKey(User, on_delete=models.CASCADE)
	date_posted = models.DateTimeField(default=timezone.now)
	price = models.IntegerField()
	bidder=models.EmailField(null=True)
	def get_absolute_url(self):
		return reverse('Items:detail', kwargs={'pk': self.pk})

# class Bid(models.Model):
# 	Item=models.ForeignKey(Item,on_delete=models.CASCADE)
# 	bid_price=models.IntegerField()
# 	bidder=models.ForeignKey(User,on_delete=models.CASCADE)

bidwar/Users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	image = models.ImageField(default='default.jpg', upload_to='profile_pics')

	def __str__(self):
		return f'{self.user.username} Profile'
	def save(self, *args, **kwargs):
		super().save(*args,**kwargs)
		img = Image.open(self.image.path)

		if img.height > 300 or img.width > 300:
			output_size = (300, 300)
			img.thumbnail(output_size)
			img.save(self.image.path)

bidwar/Items/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
	class Meta:
		model=Item
		fields=[
		'name',
		'description',
		'date_posted',
		'owner',
		'price']

class BidForm(forms.ModelForm):
	class Meta:
		model=Item
		fields=[
		'price',
		'bidder']

bidwar/Users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
  email = forms.EmailField()
 
  class Meta:
      model = User
      fields = [
      'username', 
      'email',
      'password1',
      'password2'
        ]
class UserUpdateForm(forms.ModelForm):
  email = forms.EmailField()
   

  class Meta:
    model = User
    fields = [
    'username', 
    'email',
      ]
class ProfileUpdateForm(forms.ModelForm):
  class Meta:
    model = Profile
    fields = ['image']

bidwar/Items/views.py
from django.shortcuts import render,get_object_or_404,HttpResponse
from .models import Item
from django.contrib.auth.models import User
from .forms import ItemForm,BidForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib import messages


class ItemList(ListView):
	model = Item
	ordering= ['-date_posted']

class ItemDetail(DetailView):
	model=Item

class ItemCreate(LoginRequiredMixin,CreateView):
	model = Item
	fields = [
		'name',
		'description',
		'price']
	def form_valid(self,form):
		form.instance.owner =self.request.user
		return super().form_valid(form)

@login_required
def bid(request,item):
	obj=Item.objects.get(pk=item)
	cur=obj.price
	form=BidForm(request.POST or None,instance=obj)
	if form.is_valid():
		if(form.cleaned_data.get('price')>cur):
			form.save()
			
			return render(request,"Items/start.html",{})
		else:
			messages.success(request, f'Enter high bid')
	cnxt={
	'form':form
	}
	return render(request,"Items/bid.html",cnxt)
class ItemDelete(LoginRequiredMixin,UserPassesTestMixin,DetailView):
	model=Item
	success_url = '/'
	def test_func(self):
		post = self.get_object()
		if self.request.user == post.owner:
			return True
		return False

def about_view(request):
	return render(request,"Items/about.html",{})

def start_view(request):
	
	last = Item.objects.order_by('-id')[:3]
	cnxt = {
	'last' : last,

	}
	return render(request,"Items/start.html",cnxt)

bidwar/Users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm,UserUpdateForm,ProfileUpdateForm
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}! You are ready to Log in')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'Users/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                    request.FILES,
                                    instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'Users/profile.html', context)

bidwar/templates/Items/about.html
{% extends "base.html" %}

{% block start %}

<h1>About us</h1>>
  
{% endblock %}

bidwar/templates/Items/bid.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block start %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Item Info</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Bid</button>
            </div>
        </form>
    </div>
{% endblock  %}

bidwar/templates/Items/item_confirm_delete.html
{% extends "base.html" %}

{% block start %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete item "{{object.name}}" ?</legend>
               
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'Items:detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock  %}

bidwar/templates/Items/item_detail.html
{% extends "base.html" %}

{% block start %}

<article class="media content-section">
  <div class="media-body">
    <div class="article-metadata">
    
      <small class="text-muted">{{ object.date_posted }}</small>
      
    </div>
    <h2 class="article-title">{{object.name  }}</h2>
    <p class="article-content">{{ object.description }}</p>
    <p class="article-content">Price:{{ object.price }}</p>
        {% if object.owner != user %}
    <div>
      <a class="btn btn-lg btn-primary text-uppercase" href="{% url 'Items:bid' object.id %}">Bid</a>
    </div>
    {% endif %}
    {% if object.owner == user %}
       <div>
       <h4 class="article-title">Bidder:{{object.bidder  }}</h4>

        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'Items:delete' object.id %}">Delete item</a>
        </div>
      {% endif %}
  </div>
</article>

  
{% endblock %}

bidwar/templates/Items/item_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block start %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Item Info</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Create</button>
            </div>
        </form>
    </div>
{% endblock  %}

bidwar/templates/Items/item_list.html
{% extends "base.html" %}

{% block start %}
{% for obj in object_list %}

<article class="media content-section">
	<img class="rounded-circle article-img" src="{{ obj.owner.profile.image.url }}">
  <div class="media-body">
    <div class="article-metadata">
     
      <small class="text-muted">{{ obj.date_posted }}</small>
    </div>
    <h2><a class="article-title" href="{% url 'Items:detail' obj.id%}">{{obj.name }}</a></h2>
    <p class="article-content">{{ obj.description}}</p>
    <p class="article-content">Price:{{ obj.price }}</p>
  </div>
</article>
{% endfor %}
<article class="media content-section">
  <div class="media-body">
    <div class="article-metadata">
      
      <small class="text-muted">End of Aution</small>
    </div>
    
  </div>
</article>

{% endblock %}

bidwar/templates/Items/start.html
{% extends "base.html" %}

{% block start %}

<p><h3>New items for aution</h3></p>
{% for obj in last %}
	<article class="media content-section">	
  <div class="media-body">
    <div class="article-metadata">
    
      <small class="text-muted">{{ obj.date_posted }}</small>
    </div>
    <h2><a class="article-title" href="{% url 'Items:detail' obj.id%}">{{obj.name }}</a></h2>
   <p class="article-content">{{ obj.description }}</p>
  </div>
</article>
{% endfor %}
<article class="media content-section">
  <div class="media-body">
    <div class="article-metadata">
      
      <small class="text-muted">End!</small>
    </div>
    
  </div>
</article>
  
      <a class="nav-item nav-link" href="{% url 'Items:add' %}">Action your Item now!</a>



{% endblock %}

bidwar/templates/Users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block start %}

    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Log In</button>
                
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Create a new Account? <a class="ml-2" href="{% url 'Users:register' %}">Sign Up</a>
            </small>
        </div>
    </div>
{% endblock  %}

bidwar/templates/Users/logout.html
{% extends "base.html" %}

{% block start %}
        <h3>You have been Logged out</h3>
        <div class="border-top pt-3">
            <small class="text-muted">
                Log in? <a class="ml-2" href="{% url 'login' %}">Log In</a>
            </small>
        </div>
   
{% endblock  %}

bidwar/templates/Users/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block start %}
      <div class="content-section">
  <div class="media">
    <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
    <div class="media-body">
      <h2 class="account-heading">{{ user.username}}</h2>
      <p class="text-secondary">{{user.email}}</p>
    </div>
  </div>
  <form method="POST" enctype="multipart/form-data">
		    {% csrf_token %}
		    <fieldset class="form-group">
		        <legend class="border-bottom mb-4">Profile info</legend>
		        {{ u_form|crispy }}
		         {{ p_form|crispy }}
		    </fieldset>
		    <div class="form-group">
		        <button class="btn btn-outline-info" type="submit">Update</button>
		    </div>
		</form>
</div>

   
{% endblock  %}

bidwar/templates/Users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block start %}

    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock  %}

bidwar/templates/base.html
{% load static %}

<!DOCTYPE HTML>
<html lang="en">
  <head>
     <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link rel="stylesheet" type="text/css" href="{% static 'Items/main.css' %}">
      <!--  <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}"> -->



   <TITLE>Online Auction System</TITLE>

  </head>
  <body>

      <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Online Auction System</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'Items:home' %}">Home</a>
              
               <a class="nav-item nav-link" href="{% url 'about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated  %}
              <a class="nav-item nav-link" href="{% url 'Items:add' %}">New Item</a>
              <a class="nav-item nav-link" href="{% url 'Users:profile' %}">My Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'Users:register' %}">Sign Up</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
</header>

        <main role="main" class="container">
          <div class="row">
            <div class="col-md-8">

              {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}

              {% block start %}{% endblock %}
            </div>
            
    </div>
</main>
  		
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>